Repository velicham-onlive/velicham-onlive.github.io, pull requests merged in 2019-05, with the labels that each got.

#32 chapter 108 impementation
  audios/108-kauthar/1-vqd-podcast-unit108.m4a
  audios/108-kauthar/2-vqd-podcast-unit108.m4a
  audios/108-kauthar/3-vqd-podcast-unit109.m4a
  audios/108-kauthar/4-vqd-podcast-unit108.m4a
  audios/108-kauthar/5-vqd-podcast-unit109.m4a
  audios/108-kauthar/6-vqd-podcast-unit109.m4a
  podcast.rss
Labels: enhancement, good first issue

#35 chapter107 implementation
  audios/105-feel/1-vqd-podcast-unit105.m4a
  audios/105-feel/10-vqd-podcast-unit105.m4a
  audios/105-feel/11-vqd-podcast-unit105.m4a
  audios/105-feel/2-vqd-podcast-unit105.mp3
  audios/105-feel/3-vqd-podcast-unit105.m4a
  audios/105-feel/4-vqd-podcast-unit105.m4a
  audios/105-feel/5-vqd-podcast-unit105.m4a
  audios/105-feel/6-vqd-podcast-unit105.m4a
  audios/105-feel/7-vqd-podcast-unit106.m4a
  audios/105-feel/8-vqd-podcast-unit105.m4a
  audios/105-feel/9-vqd-podcast-unit105.m4a
  audios/106-quraish/1-vqd-podcast-unit106.m4a
  audios/106-quraish/2-vqd-podcast-unit106.m4a
  audios/106-quraish/3-vqd-podcast-unit106.m4a
  audios/106-quraish/4-vqd-podcast-unit106.m4a
  audios/106-quraish/5-vqd-podcast-unit106.m4a
  audios/106-quraish/6-vqd-podcast-unit106.m4a
  audios/106-quraish/7-vqd-podcast-unit106.m4a
  audios/106-quraish/8-vqd-podcast-unit106.m4a
  audios/106-quraish/9-vqd-podcast-unit106.m4a
  audios/107-maoon/1-vqd-podcast-unit107.m4a
  audios/107-maoon/10-vqd-podcast-unit107.m4a
  audios/107-maoon/11-vqd-podcast-unit107.m4a
  audios/107-maoon/12-vqd-podcast-unit107.m4a
  audios/107-maoon/13-vqd-podcast-unit107.m4a
  audios/107-maoon/14-vqd-podcast-unit107.m4a
  audios/107-maoon/2-vqd-podcast-unit107.m4a
  audios/107-maoon/3-vqd-podcast-unit107.m4a
  audios/107-maoon/4-vqd-podcast-unit107.m4a
  audios/107-maoon/5-vqd-podcast-unit107.m4a
  audios/107-maoon/6-vqd-podcast-unit107.m4a
  audios/107-maoon/7-vqd-podcast-unit107.m4a
  audios/107-maoon/8-vqd-podcast-unit107.m4a
  audios/107-maoon/9-vqd-podcast-unit107.m4a
  podcast.rss
Labels: enhancement, good first issue, help wanted

#37 Chapter 104
  audios/104-humaza/1-vqd-podcast-unit104.m4a
  audios/104-humaza/10-vqd-podcast-unit104.m4a
  audios/104-humaza/2-vqd-podcast-unit104.m4a
  audios/104-humaza/3-vqd-podcast-unit104.m4a
  audios/104-humaza/4-vqd-podcast-unit104.m4a
  audios/104-humaza/5-vqd-podcast-unit104.m4a
  audios/104-humaza/6-vqd-podcast-unit104.m4a
  audios/104-humaza/7-vqd-podcast-unit104.m4a
  audios/104-humaza/8-vqd-podcast-unit104.m4a
  audios/104-humaza/9-vqd-podcast-unit104.mp3
  podcast.rss
Labels: enhancement, good first issue, help wanted

#38 Chapter 103 implementation
  audios/103-asr/1-vqd-podcast-unit103.m4a
  audios/103-asr/10-vqd-podcast-unit103.m4a
  audios/103-asr/11-vqd-podcast-unit103.m4a
  audios/103-asr/12-vqd-podcast-unit103.m4a
  audios/103-asr/13-vqd-podcast-unit103.m4a
  audios/103-asr/14-vqd-podcast-unit103.m4a
  audios/103-asr/15-vqd-podcast-unit103.m4a
  audios/103-asr/16-vqd-podcast-unit103.m4a
  audios/103-asr/2-vqd-podcast-unit103.mp3
  audios/103-asr/3-vqd-podcast-unit103.m4a
  audios/103-asr/4-vqd-podcast-unit103.m4a
  audios/103-asr/5-vqd-podcast-unit103.m4a
  audios/103-asr/6-vqd-podcast-unit103.mp3
  audios/103-asr/7-vqd-podcast-unit103.m4a
  audios/103-asr/8-vqd-podcast-unit103.m4a
  audios/103-asr/9-vqd-podcast-unit103.m4a
  podcast.rss
Labels: enhancement, good first issue, help wanted

#39 chapter 102 implementation
  audios/102-takathur/1-vqd-podcast-unit102.m4a
  audios/102-takathur/10-vqd-podcast-unit102.m4a
  audios/102-takathur/11-vqd-podcast-unit102.m4a
  audios/102-takathur/12-vqd-podcast-unit102.m4a
  audios/102-takathur/13-vqd-podcast-unit102.m4a
  audios/102-takathur/14-vqd-podcast-unit102.m4a
  audios/102-takathur/15-vqd-podcast-unit102.m4a
  audios/102-takathur/16-vqd-podcast-unit102.m4a
  audios/102-takathur/17-vqd-podcast-unit102.m4a
  audios/102-takathur/2-vqd-podcast-unit102.m4a
  audios/102-takathur/3-vqd-podcast-unit102.m4a
  audios/102-takathur/4-vqd-podcast-unit102.m4a
  audios/102-takathur/5-vqd-podcast-unit102.m4a
  audios/102-takathur/6-vqd-podcast-unit102.m4a
  audios/102-takathur/7-vqd-podcast-unit102.m4a
  audios/102-takathur/8-vqd-podcast-unit102.m4a
  audios/102-takathur/9-vqd-podcast-unit102.m4a
  podcast.rss
Labels: enhancement, good first issue, help wanted

#44 Chapter 101 Implementation
  audios/101-qaria/1-vqd-podcast-unit101.m4a
  audios/101-qaria/10-vqd-podcast-unit101.m4a
  audios/101-qaria/2-vqd-podcast-unit101.m4a
  audios/101-qaria/3-vqd-podcast-unit101.m4a
  audios/101-qaria/4-vqd-podcast-unit101.m4a
  audios/101-qaria/5-vqd-podcast-unit101.m4a
  audios/101-qaria/6-vqd-podcast-unit101.m4a
  audios/101-qaria/7-vqd-podcast-unit101.m4a
  audios/101-qaria/8-vqd-podcast-unit101.m4a
  audios/101-qaria/9-vqd-podcast-unit101.m4a
  podcast.rss
Labels: duplicate, enhancement, good first issue, help wanted

#42 Chapter 100 implementation
  audios/100-adiyath/1-vqd-podcast-unit100.m4a
  audios/100-adiyath/10-vqd-podcast-unit100.m4a
  audios/100-adiyath/11-vqd-podcast-unit100.m4a
  audios/100-adiyath/12-vqd-podcast-unit100.m4a
  audios/100-adiyath/13-vqd-podcast-unit100.m4a
  audios/100-adiyath/14-vqd-podcast-unit100.m4a
  audios/100-adiyath/15-vqd-podcast-unit100.m4a
  audios/100-adiyath/2-vqd-podcast-unit100.m4a
  audios/100-adiyath/3-vqd-podcast-unit100.m4a
  audios/100-adiyath/4-vqd-podcast-unit100.m4a
  audios/100-adiyath/5-vqd-podcast-unit100.m4a
  audios/100-adiyath/6-vqd-podcast-unit100.m4a
  audios/100-adiyath/7-vqd-podcast-unit100.m4a
  audios/100-adiyath/8-vqd-podcast-unit100.m4a
  audios/100-adiyath/9-vqd-podcast-unit100.m4a
  podcast.rss
Labels: enhancement, good first issue, help wanted

#43 Chapter 99 implementation
  audios/99-zalzala/1-vqd-podcast-unit99.m4a
  audios/99-zalzala/10-vqd-podcast-unit99.m4a
  audios/99-zalzala/11-vqd-podcast-unit99.m4a
  audios/99-zalzala/12-vqd-podcast-unit99.m4a
  audios/99-zalzala/13-vqd-podcast-unit99.m4a
  audios/99-zalzala/14-vqd-podcast-unit99.m4a
  audios/99-zalzala/15-vqd-podcast-unit99.m4a
  audios/99-zalzala/16-vqd-podcast-unit99.m4a
  audios/99-zalzala/17-vqd-podcast-unit99.m4a
  audios/99-zalzala/18-vqd-podcast-unit99.m4a
  audios/99-zalzala/19-vqd-podcast-unit99.m4a
  audios/99-zalzala/2-vqd-podcast-unit99.m4a
  audios/99-zalzala/20-vqd-podcast-unit99.m4a
  audios/99-zalzala/21-vqd-podcast-unit99.m4a
  audios/99-zalzala/22-vqd-podcast-unit99.m4a
  audios/99-zalzala/23-vqd-podcast-unit99.m4a
  audios/99-zalzala/24-vqd-podcast-unit99.m4a
  audios/99-zalzala/3-vqd-podcast-unit99.m4a
  audios/99-zalzala/4-vqd-podcast-unit99.m4a
  audios/99-zalzala/5-vqd-podcast-unit99.m4a
  audios/99-zalzala/6-vqd-podcast-unit99.m4a
  audios/99-zalzala/7-vqd-podcast-unit99.m4a
  audios/99-zalzala/8-vqd-podcast-unit99.m4a
  audios/99-zalzala/9-vqd-podcast-unit99.m4a
  podcast.rss
Labels: enhancement, good first issue, help wanted

#46 chapter98implementation
  audios/98-bayyinah/1-vqd-podcast-unit98.mp3
  audios/98-bayyinah/10-vqd-podcast-unit98.m4a
  audios/98-bayyinah/11-vqd-podcast-unit98.m4a
  audios/98-bayyinah/12-vqd-podcast-unit98.m4a
  audios/98-bayyinah/13-vqd-podcast-unit98.m4a
  audios/98-bayyinah/14-vqd-podcast-unit98.m4a
  audios/98-bayyinah/15-vqd-podcast-unit98.m4a
  audios/98-bayyinah/16-vqd-podcast-unit98.mp3
  audios/98-bayyinah/17-vqd-podcast-unit98.m4a
  audios/98-bayyinah/18-vqd-podcast-unit98.m4a
  audios/98-bayyinah/19-vqd-podcast-unit98.m4a
  audios/98-bayyinah/2-vqd-podcast-unit98.m4a
  audios/98-bayyinah/20-vqd-podcast-unit98.m4a
  audios/98-bayyinah/21-vqd-podcast-unit98.m4a
  audios/98-bayyinah/22-vqd-podcast-unit98.m4a
  audios/98-bayyinah/23-vqd-podcast-unit98.m4a
  audios/98-bayyinah/24-vqd-podcast-unit98.m4a
  audios/98-bayyinah/25-vqd-podcast-unit98.m4a
  audios/98-bayyinah/26-vqd-podcast-unit98.m4a
  audios/98-bayyinah/27-vqd-podcast-unit98.m4a
  audios/98-bayyinah/28-vqd-podcast-unit98.m4a
  audios/98-bayyinah/29-vqd-podcast-unit98.m4a
  audios/98-bayyinah/3-vqd-podcast-unit98.m4a
  audios/98-bayyinah/30-vqd-podcast-unit98.m4a
  audios/98-bayyinah/31-vqd-podcast-unit98.m4a
  audios/98-bayyinah/32-vqd-podcast-unit98.m4a
  audios/98-bayyinah/33-vqd-podcast-unit98.m4a
  audios/98-bayyinah/34-vqd-podcast-unit98.mp3
  audios/98-bayyinah/4-vqd-podcast-unit98.m4a
  audios/98-bayyinah/5-vqd-podcast-unit98.m4a
  audios/98-bayyinah/6-vqd-podcast-unit98.m4a
  audios/98-bayyinah/7-vqd-podcast-unit98.m4a
  audios/98-bayyinah/8-vqd-podcast-unit98.m4a
  audios/98-bayyinah/9-vqd-podcast-unit98.mp3
  podcast.rss
Labels: enhancement, good first issue, help wanted

#47 chapter97implementation
  audios/97-qadr/1-vqd-podcast-unit97.m4a
  audios/97-qadr/10-vqd-podcast-unit97.mp3
  audios/97-qadr/11-vqd-podcast-unit97.m4a
  audios/97-qadr/12-vqd-podcast-unit97.m4a
  audios/97-qadr/13-vqd-podcast-unit97.m4a
  audios/97-qadr/14-vqd-podcast-unit97.m4a
  audios/97-qadr/15-vqd-podcast-unit97.m4a
  audios/97-qadr/16-vqd-podcast-unit97.m4a
  audios/97-qadr/2-vqd-podcast-unit97.m4a
  audios/97-qadr/3-vqd-podcast-unit97.m4a
  audios/97-qadr/4-vqd-podcast-unit97.m4a
  audios/97-qadr/5-vqd-podcast-unit97.m4a
  audios/97-qadr/6-vqd-podcast-unit97.m4a
  audios/97-qadr/7-vqd-podcast-unit97.m4a
  audios/97-qadr/8-vqd-podcast-unit97.mp3
  audios/97-qadr/9-vqd-podcast-unit97.m4a
  podcast.rss
Labels: enhancement, good first issue, help wanted

#50 chapter 95 implementation
  audios/95-atheen/1-vqd-podcast-unit95.m4a
  audios/95-atheen/10-vqd-podcast-unit95.m4a
  audios/95-atheen/11-vqd-podcast-unit95.m4a
  audios/95-atheen/12-vqd-podcast-unit95.m4a
  audios/95-atheen/13-vqd-podcast-unit95.m4a
  audios/95-atheen/14-vqd-podcast-unit95.m4a
  audios/95-atheen/15-vqd-podcast-unit95.m4a
  audios/95-atheen/16-vqd-podcast-unit95.m4a
  audios/95-atheen/2-vqd-podcast-unit95.m4a
  audios/95-atheen/3-vqd-podcast-unit95.m4a
  audios/95-atheen/4-vqd-podcast-unit95.m4a
  audios/95-atheen/5-vqd-podcast-unit95.m4a
  audios/95-atheen/6-vqd-podcast-unit95.m4a
  audios/95-atheen/7-vqd-podcast-unit95.m4a
  audios/95-atheen/8-vqd-podcast-unit95.m4a
  audios/95-atheen/9-vqd-podcast-unit95.m4a
  podcast.rss
Labels: enhancement, good first issue, help wanted

#52 Chapter 94 implementation
  audios/94-sharh/1-vqd-podcast-unit94.m4a
  audios/94-sharh/10-vqd-podcast-unit94.mp3
  audios/94-sharh/11-vqd-podcast-unit94.m4a
  audios/94-sharh/12-vqd-podcast-unit94.m4a
  audios/94-sharh/13-vqd-podcast-unit94.m4a
  audios/94-sharh/14-vqd-podcast-unit94.m4a
  audios/94-sharh/15-vqd-podcast-unit94.m4a
  audios/94-sharh/2-vqd-podcast-unit94.m4a
  audios/94-sharh/3-vqd-podcast-unit94.m4a
  audios/94-sharh/4-vqd-podcast-unit94.m4a
  audios/94-sharh/5-vqd-podcast-unit94.m4a
  audios/94-sharh/6-vqd-podcast-unit94.m4a
  audios/94-sharh/7-vqd-podcast-unit94.m4a
  audios/94-sharh/8-vqd-podcast-unit94.m4a
  audios/94-sharh/9-vqd-podcast-unit94.m4a
  podcast.rss
Labels: enhancement, good first issue, help wanted

#53 Chapter 93 implementation
  audios/93-dhuhaa/1-vqd-podcast-unit93.m4a
  audios/93-dhuhaa/10-vqd-podcast-unit93.m4a
  audios/93-dhuhaa/11-vqd-podcast-unit93.m4a
  audios/93-dhuhaa/12-vqd-podcast-unit93.m4a
  audios/93-dhuhaa/13-vqd-podcast-unit93.m4a
  audios/93-dhuhaa/14-vqd-podcast-unit93.m4a
  audios/93-dhuhaa/15-vqd-podcast-unit93.m4a
  audios/93-dhuhaa/2-vqd-podcast-unit93.m4a
  audios/93-dhuhaa/3-vqd-podcast-unit93.m4a
  audios/93-dhuhaa/4-vqd-podcast-unit93.m4a
  audios/93-dhuhaa/5-vqd-podcast-unit93.m4a
  audios/93-dhuhaa/6-vqd-podcast-unit93.m4a
  audios/93-dhuhaa/7-vqd-podcast-unit93.m4a
  audios/93-dhuhaa/8-vqd-podcast-unit93.m4a
  audios/93-dhuhaa/9-vqd-podcast-unit93.m4a
  podcast.rss
Labels: enhancement, good first issue, help wanted

#54 chapter 92 implementation
  audios/92-layl/1-vqd-podcast-unit92.m4a
  audios/92-layl/10-vqd-podcast-unit92.m4a
  audios/92-layl/11-vqd-podcast-unit92.m4a
  audios/92-layl/12-vqd-podcast-unit92.m4a
  audios/92-layl/13-vqd-podcast-unit92.m4a
  audios/92-layl/14-vqd-podcast-unit92.m4a
  audios/92-layl/15-vqd-podcast-unit92.m4a
  audios/92-layl/16-vqd-podcast-unit92.m4a
  audios/92-layl/17-vqd-podcast-unit92.m4a
  audios/92-layl/18-vqd-podcast-unit92.m4a
  audios/92-layl/19-vqd-podcast-unit92.m4a
  audios/92-layl/2-vqd-podcast-unit92.m4a
  audios/92-layl/20-vqd-podcast-unit92.m4a
  audios/92-layl/21-vqd-podcast-unit92.m4a
  audios/92-layl/22-vqd-podcast-unit92.mp3
  audios/92-layl/23-vqd-podcast-unit92.m4a
  audios/92-layl/24-vqd-podcast-unit92.m4a
  audios/92-layl/25-vqd-podcast-unit92.m4a
  audios/92-layl/26-vqd-podcast-unit92.m4a
  audios/92-layl/27-vqd-podcast-unit92.m4a
  audios/92-layl/28-vqd-podcast-unit92.m4a
  audios/92-layl/3-vqd-podcast-unit92.m4a
  audios/92-layl/4-vqd-podcast-unit92.m4a
  audios/92-layl/5-vqd-podcast-unit92.m4a
  audios/92-layl/6-vqd-podcast-unit92.m4a
  audios/92-layl/7-vqd-podcast-unit92.m4a
  audios/92-layl/8-vqd-podcast-unit92.m4a
  audios/92-layl/9-vqd-podcast-unit92.m4a
  podcast.rss
Labels: enhancement, good first issue, help wanted

#56 chapter 91 implementation
  audios/91-shams/1-vqd-podcast-unit91.mp3
  audios/91-shams/10-vqd-podcast-unit91.m4a
  audios/91-shams/11-vqd-podcast-unit91.mp3
  audios/91-shams/12-vqd-podcast-unit91.m4a
  audios/91-shams/13-vqd-podcast-unit91.m4a
  audios/91-shams/14-vqd-podcast-unit91.m4a
  audios/91-shams/15-vqd-podcast-unit91.mp3
  audios/91-shams/16-vqd-podcast-unit91.mp3
  audios/91-shams/17-vqd-podcast-unit91.m4a
  audios/91-shams/18-vqd-podcast-unit91.m4a
  audios/91-shams/19-vqd-podcast-unit91.m4a
  audios/91-shams/2-vqd-podcast-unit91.m4a
  audios/91-shams/20-vqd-podcast-unit91.mp3
  audios/91-shams/3-vqd-podcast-unit91.m4a
  audios/91-shams/4-vqd-podcast-unit91.m4a
  audios/91-shams/5-vqd-podcast-unit91.m4a
  audios/91-shams/6-vqd-podcast-unit91.m4a
  audios/91-shams/7-vqd-podcast-unit91.m4a
  audios/91-shams/8-vqd-podcast-unit91.m4a
  audios/91-shams/9-vqd-podcast-unit91.m4a
  podcast.rss
Labels: good first issue, help wanted, invalid

#62 Chapter 90 implementation
  audios/90-balad/1-vqd-podcast-unit90.mp3
  audios/90-balad/10-vqd-podcast-unit90.mp3
  audios/90-balad/11-vqd-podcast-unit90.mp3
  audios/90-balad/12-vqd-podcast-unit90.mp3
  audios/90-balad/13-vqd-podcast-unit90.mp3
  audios/90-balad/14-vqd-podcast-unit90.mp3
  audios/90-balad/15-vqd-podcast-unit90.mp3
  audios/90-balad/16-vqd-podcast-unit90.mp3
  audios/90-balad/17-vqd-podcast-unit90.mp3
  audios/90-balad/18-vqd-podcast-unit90.mp3
  audios/90-balad/19-vqd-podcast-unit90.mp3
  audios/90-balad/2-vqd-podcast-unit90.mp3
  audios/90-balad/20-vqd-podcast-unit90.mp3
  audios/90-balad/21-vqd-podcast-unit90.mp3
  audios/90-balad/22-vqd-podcast-unit90.mp3
  audios/90-balad/23-vqd-podcast-unit90.mp3
  audios/90-balad/24-vqd-podcast-unit90.mp3
  audios/90-balad/3-vqd-podcast-unit90.mp3
  audios/90-balad/4-vqd-podcast-unit90.mp3
  audios/90-balad/5-vqd-podcast-unit90.mp3
  audios/90-balad/6-vqd-podcast-unit90.mp3
  audios/90-balad/7-vqd-podcast-unit90.mp3
  audios/90-balad/8-vqd-podcast-unit90.mp3
  audios/90-balad/9-vqd-podcast-unit90.mp3
  podcast.rss
Labels: enhancement, good first issue, help wanted

#63 Chapter 89 implementation
  audios/89-fajr/1-vqd-podcast-unit89.mp3
  audios/89-fajr/10-vqd-podcast-unit89.mp3
  audios/89-fajr/11-vqd-podcast-unit89.m4a
  audios/89-fajr/12-vqd-podcast-unit89.mp3
  audios/89-fajr/13-vqd-podcast-unit89.mp3
  audios/89-fajr/14-vqd-podcast-unit89.m4a
  audios/89-fajr/15-vqd-podcast-unit89.mp3
  audios/89-fajr/16-vqd-podcast-unit89.mp3
  audios/89-fajr/17-vqd-podcast-unit89.m4a
  audios/89-fajr/18-vqd-podcast-unit89.m4a
  audios/89-fajr/19-vqd-podcast-unit89.m4a
  audios/89-fajr/2-vqd-podcast-unit89.mp3
  audios/89-fajr/20-vqd-podcast-unit89.m4a
  audios/89-fajr/21-vqd-podcast-unit89.m4a
  audios/89-fajr/22-vqd-podcast-unit89.m4a
  audios/89-fajr/23-vqd-podcast-unit89.mp3
  audios/89-fajr/24-vqd-podcast-unit89.m4a
  audios/89-fajr/25-vqd-podcast-unit89.m4a
  audios/89-fajr/26-vqd-podcast-unit89.m4a
  audios/89-fajr/27-vqd-podcast-unit89.mp3
  audios/89-fajr/3-vqd-podcast-unit89.mp3
  audios/89-fajr/4-vqd-podcast-unit89.mp3
  audios/89-fajr/5-vqd-podcast-unit89.mp3
  audios/89-fajr/6-vqd-podcast-unit89.mp3
  audios/89-fajr/7-vqd-podcast-unit89.mp3
  audios/89-fajr/8-vqd-podcast-unit89.mp3
  audios/89-fajr/9-vqd-podcast-unit89.m4a
  podcast.rss
Labels: enhancement, good first issue, help wanted

#64 Chapter 88 implementation
  audios/88-ghashiya/1-vqd-podcast-unit88.m4a
  audios/88-ghashiya/10-vqd-podcast-unit88.amr
  audios/88-ghashiya/11-vqd-podcast-unit88.m4a
  audios/88-ghashiya/12-vqd-podcast-unit88.amr
  audios/88-ghashiya/13-vqd-podcast-unit88.amr
  audios/88-ghashiya/14-vqd-podcast-unit88.amr
  audios/88-ghashiya/2-vqd-podcast-unit88.mp3
  audios/88-ghashiya/3-vqd-podcast-unit88.mp3
  audios/88-ghashiya/4-vqd-podcast-unit88.mp3
  audios/88-ghashiya/5-vqd-podcast-unit88.mp3
  audios/88-ghashiya/6-vqd-podcast-unit88.m4a
  audios/88-ghashiya/7-vqd-podcast-unit88.mp3
  audios/88-ghashiya/8-vqd-podcast-unit88.mp3
  audios/88-ghashiya/9-vqd-podcast-unit88.mp3
  podcast.rss
Labels: enhancement, good first issue, help wanted

#65 Chapter 87 implementation
  audios/87-aala/1-vqd-podcast-unit87.m4a
  audios/87-aala/10-vqd-podcast-unit87.m4a
  audios/87-aala/11-vqd-podcast-unit87.m4a
  audios/87-aala/12-vqd-podcast-unit87.m4a
  audios/87-aala/13-vqd-podcast-unit87.m4a
  audios/87-aala/14-vqd-podcast-unit87.m4a
  audios/87-aala/15-vqd-podcast-unit87.m4a
  audios/87-aala/16-vqd-podcast-unit87.m4a
  audios/87-aala/2-vqd-podcast-unit87.m4a
  audios/87-aala/3-vqd-podcast-unit87.m4a
  audios/87-aala/4-vqd-podcast-unit87.m4a
  audios/87-aala/5-vqd-podcast-unit87.m4a
  audios/87-aala/6-vqd-podcast-unit87.m4a
  audios/87-aala/7-vqd-podcast-unit87.m4a
  audios/87-aala/8-vqd-podcast-unit87.m4a
  audios/87-aala/9-vqd-podcast-unit87.m4a
  podcast.rss
Labels: enhancement, good first issue, help wanted

#66 Chapter 86 implementation
  audios/86-tariq/1-vqd-podcast-unit86.mp3
  audios/86-tariq/10-vqd-podcast-unit86.mp3
  audios/86-tariq/2-vqd-podcast-unit86.mp3
  audios/86-tariq/3-vqd-podcast-unit86.mp3
  audios/86-tariq/4-vqd-podcast-unit86.mp3
  audios/86-tariq/5-vqd-podcast-unit86.mp3
  audios/86-tariq/6-vqd-podcast-unit86.mp3
  audios/86-tariq/7-vqd-podcast-unit86.mp3
  audios/86-tariq/8-vqd-podcast-unit86.mp3
  audios/86-tariq/9-vqd-podcast-unit86.mp3
  podcast.rss
Labels: enhancement, good first issue, help wanted

#67 Chapter 85 implementation
  audios/85-burooj/1-vqd-podcast-unit85.mp3
  audios/85-burooj/10-vqd-podcast-unit85.mp3
  audios/85-burooj/11-vqd-podcast-unit85.mp3
  audios/85-burooj/12-vqd-podcast-unit85.mp3
  audios/85-burooj/13-vqd-podcast-unit85.mp3
  audios/85-burooj/14-vqd-podcast-unit85.mp3
  audios/85-burooj/2-vqd-podcast-unit85.mp3
  audios/85-burooj/3-vqd-podcast-unit85.mp3
  audios/85-burooj/4-vqd-podcast-unit85.mp3
  audios/85-burooj/5-vqd-podcast-unit85.mp3
  audios/85-burooj/6-vqd-podcast-unit85.mp3
  audios/85-burooj/7-vqd-podcast-unit85.mp3
  audios/85-burooj/8-vqd-podcast-unit85.mp3
  audios/85-burooj/9-vqd-podcast-unit85.mp3
  podcast.rss
Labels: enhancement, good first issue, help wanted

#70 Chapter 87 audio correction
  audios/87-aala/1-vqd-podcast-unit87.m4a
  audios/87-aala/1-vqd-podcast-unit87.mp3
  audios/87-aala/10-vqd-podcast-unit87.m4a
  audios/87-aala/10-vqd-podcast-unit87.mp3
  audios/87-aala/11-vqd-podcast-unit87.m4a
  audios/87-aala/11-vqd-podcast-unit87.mp3
  audios/87-aala/12-vqd-podcast-unit87.m4a
  audios/87-aala/12-vqd-podcast-unit87.mp3
  audios/87-aala/13-vqd-podcast-unit87.m4a
  audios/87-aala/13-vqd-podcast-unit87.mp3
  audios/87-aala/14-vqd-podcast-unit87.m4a
  audios/87-aala/14-vqd-podcast-unit87.mp3
  audios/87-aala/15-vqd-podcast-unit87.m4a
  audios/87-aala/15-vqd-podcast-unit87.mp3
  audios/87-aala/16-vqd-podcast-unit87.m4a
  audios/87-aala/16-vqd-podcast-unit87.mp3
  audios/87-aala/2-vqd-podcast-unit87.m4a
  audios/87-aala/3-vqd-podcast-unit87.m4a
  audios/87-aala/3-vqd-podcast-unit87.mp3
  audios/87-aala/4-vqd-podcast-unit87.m4a
  audios/87-aala/4-vqd-podcast-unit87.mp3
  audios/87-aala/5-vqd-podcast-unit87.m4a
  audios/87-aala/5-vqd-podcast-unit87.mp3
  audios/87-aala/6-vqd-podcast-unit87.m4a
  audios/87-aala/6-vqd-podcast-unit87.mp3
  audios/87-aala/7-vqd-podcast-unit87.m4a
  audios/87-aala/7-vqd-podcast-unit87.mp3
  audios/87-aala/8-vqd-podcast-unit87.m4a
  audios/87-aala/8-vqd-podcast-unit87.mp3
  audios/87-aala/9-vqd-podcast-unit87.m4a
  audios/87-aala/9-vqd-podcast-unit87.mp3
  podcast.rss
Labels: bug, good first issue, help wanted

#73 Chapter 83 implementation
  audios/83-mutaffifin/1-vqd-podcast-unit83.mp3
  audios/83-mutaffifin/10-vqd-podcast-unit83.mp3
  audios/83-mutaffifin/11-vqd-podcast-unit83.mp3
  audios/83-mutaffifin/12-vqd-podcast-unit83.mp3
  audios/83-mutaffifin/13-vqd-podcast-unit83.mp3
  audios/83-mutaffifin/14-vqd-podcast-unit83.mp3
  audios/83-mutaffifin/15-vqd-podcast-unit83.mp3
  audios/83-mutaffifin/16-vqd-podcast-unit83.mp3
  audios/83-mutaffifin/17-vqd-podcast-unit83.mp3
  audios/83-mutaffifin/18-vqd-podcast-unit83.mp3
  audios/83-mutaffifin/19-vqd-podcast-unit83.mp3
  audios/83-mutaffifin/2-vqd-podcast-unit83.mp3
  audios/83-mutaffifin/20-vqd-podcast-unit83.mp3
  audios/83-mutaffifin/21-vqd-podcast-unit83.mp3
  audios/83-mutaffifin/22-vqd-podcast-unit83.mp3
  audios/83-mutaffifin/23-vqd-podcast-unit83.mp3
  audios/83-mutaffifin/24-vqd-podcast-unit83.mp3
  audios/83-mutaffifin/25-vqd-podcast-unit83.mp3
  audios/83-mutaffifin/26-vqd-podcast-unit83.mp3
  audios/83-mutaffifin/27-vqd-podcast-unit83.mp3
  audios/83-mutaffifin/28-vqd-podcast-unit83.mp3
  audios/83-mutaffifin/29-vqd-podcast-unit83.mp3
  audios/83-mutaffifin/3-vqd-podcast-unit83.mp3
  audios/83-mutaffifin/30-vqd-podcast-unit83.mp3
  audios/83-mutaffifin/31-vqd-podcast-unit83.mp3
  audios/83-mutaffifin/32-vqd-podcast-unit83.mp3
  audios/83-mutaffifin/4-vqd-podcast-unit83.mp3
  audios/83-mutaffifin/5-vqd-podcast-unit83.mp3
  audios/83-mutaffifin/6-vqd-podcast-unit83.mp3
  audios/83-mutaffifin/7-vqd-podcast-unit83.mp3
  audios/83-mutaffifin/8-vqd-podcast-unit83.mp3
  audios/83-mutaffifin/9-vqd-podcast-unit83.mp3
  podcast.rss
Labels: enhancement, good first issue, help wanted

#74 Chapter 82 implementation
  audios/82-infitar/1-vqd-podcast-unit82.mp3
  audios/82-infitar/10-vqd-podcast-unit82.mp3
  audios/82-infitar/11-vqd-podcast-unit82.mp3
  audios/82-infitar/12-vqd-podcast-unit82.mp3
  audios/82-infitar/13-vqd-podcast-unit82.mp3
  audios/82-infitar/2-vqd-podcast-unit82.mp3
  audios/82-infitar/3-vqd-podcast-unit82.mp3
  audios/82-infitar/4-vqd-podcast-unit82.mp3
  audios/82-infitar/5-vqd-podcast-unit82.mp3
  audios/82-infitar/6-vqd-podcast-unit82.mp3
  audios/82-infitar/7-vqd-podcast-unit82.mp3
  audios/82-infitar/8-vqd-podcast-unit82.mp3
  audios/82-infitar/9-vqd-podcast-unit82.mp3
  podcast.rss
Labels: enhancement, good first issue, help wanted
